name: atproto

command:
  bootstrap:
    usePubspecOverrides: true

packages:
  - website/**
  - packages/**
  - examples/**

scripts:
  setup:
    run: |
      melos get
      melos build
    description: Set up the atproto.dart project when cloned. Run `dart pub get` and `dart run build_runner build` in all Dart packages.

  get:
    run: melos exec -c 20 -- \
           dart pub get
    description: Run `dart pub get` command in all packages.

  analyze:
    run: |
      melos exec -c 20 -- \
        flutter analyze .
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  format:
    run: |
      melos exec -c 20 -- \
        dart format .
      melos exec --depends-on="import_sorter" -c 20 -- \
        dart run import_sorter:main
    description: Run `dart format` and `dart run import_sorter:main` in all packages.

  build:
    run: |
      melos exec --depends-on="build_runner" -c 20 -- \
        dart run build_runner build clean
      melos exec --depends-on="build_runner" -c 1 -- \
        dart run build_runner build --delete-conflicting-outputs
    description: Run `dart run build_runner build` in all packages.

  test:
    run: melos exec  -c 20 --fail-fast -- "\$MELOS_ROOT_PATH/scripts/coverage.sh"
    description: Run all Dart tests in this project.
    flutter: false
    dir-exists: test

  publish_all:
    run: |
      melos publish
      melos publish --no-dry-run --git-tag-version
      git push origin --tags
    description: Publish all packages, create git tags and push them to origin.
