name: atproto

command:
  bootstrap:
    usePubspecOverrides: true

packages:
  - website/**
  - packages/**
  - examples/**

scripts:
  get:
    run: melos exec -c 1 -- \
           flutter pub get
    description: Run pub get command in this project.

  analyze:
    run: |
      melos exec -c 10 -- \
        flutter analyze .
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  format:
    run: |
      melos exec -c 10 -- \
        dart format .
    description: |
      Run `dart format` in all packages.

  import_sorter:
    run: |
      melos exec -c 10 -- \
        dart pub run import_sorter:main
    description: |
      Run `dart run import_sorter:main` in all packages.

  build_runner:
    run: |
      melos exec -c 10 -- \
        dart run build_runner build --delete-conflicting-outputs
    description: Run build_runner and melos format in all packages.

  test:
    run: melos run test:dart --no-select && melos run test:flutter --no-select
    description: Run all Dart & Flutter tests in this project.
    dir-exists: test

  test:dart:
    run: melos exec  -c 10 --fail-fast -- "\$MELOS_ROOT_PATH/scripts/coverage.sh"
    description: Run Dart tests for a specific package in this project.
    select-package:
      flutter: false
      dir-exists: test

  test:flutter:
    run: melos exec --dir-exists="test" -c 1 --fail-fast -- "flutter test --coverage"
    description: Run Flutter tests for a specific package in this project.
    select-package:
      flutter: true
      dir-exists: test

  publish_all:
    run: |
      melos publish
      melos publish --no-dry-run --git-tag-version
      git push origin --tags
    description: Publish all packages, create git tags and push them to origin.
