// Copyright 2023 Shinya Kato. All rights reserved.
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided the conditions.

// ignore_for_file: invalid_annotation_target

// 📦 Package imports:
import 'package:atproto_core/atproto_core.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'generator_feed.freezed.dart';
part 'generator_feed.g.dart';

/// [GeneratorFeed] class represents a feed generated by a specific actor.
///
/// This class is generated using the Freezed package. It contains a URI that
/// represents a specific feed.
@freezed
class GeneratorFeed with _$GeneratorFeed {
  /// Creates an instance of [GeneratorFeed].
  ///
  /// Requires a URI that represents the feed.
  @JsonSerializable(includeIfNull: false)
  const factory GeneratorFeed({
    /// The URI of the feed.
    @AtUriConverter() required AtUri uri,
  }) = _GeneratorFeed;

  /// Creates an instance of [GeneratorFeed] from a map [json].
  ///
  /// This map [json] should contain all the fields necessary to instantiate
  /// the class.
  factory GeneratorFeed.fromJson(Map<String, Object?> json) =>
      _$GeneratorFeedFromJson(json);
}
