name: Bug Report
description: Report a bug you encountered while using atproto.dart packages
title: "[Bug]: "
labels: ["bug", "untriaged"]
assignees:
  - myConsciousness
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us investigate and fix the issue.

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is affected by this bug?
      options:
        - atproto
        - atproto_core
        - atproto_oauth
        - atproto_test
        - bluesky
        - bluesky_cli
        - bluesky_text
        - did_plc
        - lex_gen
        - lexicon
        - multiformats
        - xrpc
        - Other/Multiple packages
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of the package are you using?
      placeholder: "e.g., 1.2.3"
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Describe what happened and what you expected to happen
      placeholder: A clear and concise description of the bug
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: A clear and concise description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: If applicable, add error logs to help explain your problem
      render: shell
      placeholder: Paste your error logs here

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: If applicable, provide a minimal code sample that reproduces the issue
      render: dart
      placeholder: |
        // Your code sample here
        void main() {
          // ...
        }

  - type: dropdown
    id: dart-version
    attributes:
      label: Dart Version
      description: What version of Dart are you using?
      options:
        - "Please specify in additional context"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you running on?
      multiple: true
      options:
        - Android
        - iOS
        - Web
        - Windows
        - macOS
        - Linux
        - Other

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, such as screenshots, related issues, or workarounds you've tried
      placeholder: Any additional information that might help us understand the issue better