name: "Send Bluesky Post"
description: "Provide an easy way to post to Bluesky Social from Github Actions."
author: 'Shinya Kato'
inputs:
  text:
    description: Text to be posted to Bluesky.
  media:
    description: File path of the media to be attached to the Post.
  media-alt:
    description: Alt Text to be assigned to uploaded Media.
  identifier:
    description: >
      Handle name or email of the user who logs into Bluesky.
      This information is used by the ATP server to establish a session.
      For example, "shinyakato.bsky.social".
  password:
    description: >
      Password of the user who logs into Bluesky.
      This information is used by the ATP server to establish a session.
  service:
    description: >
      Specify the authority of the ATP server to which you wish to post.
      If omitted, it will always be "bsky.social".
  retry-count:
    description: >
      Specify the number of retry on server error or network error.
      If omitted, it will always be "5".

runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: edit
  color: blue
