name: snippets
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.3

# Add regular dependencies here.
dependencies:
  bluesky: ^0.6.0
  bluesky_text: ^0.2.2
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^2.0.0
