name: Pull Latest Lexicons

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"

jobs:
  pull-lexicons:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Delete Old Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin
          if git show-ref --quiet refs/remotes/origin/pull-latest-lexicons; then
            git push origin --delete pull-latest-lexicons
          fi

      - name: Create New Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch -c pull-latest-lexicons
          git push -u origin pull-latest-lexicons

      - uses: dart-lang/setup-dart@v1.3
      - name: Install dependencies
        run: dart pub get

      - name: Pull Latest Lexicons
        run: dart run ./bin/pull_latest_lexicons.dart
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Generate Lexicon IDs
        run: dart run ./bin/generate_lexicon_ids.dart

      - name: Generate Lexicon Matrix
        run: dart run ./bin/generate_lexicon_matrix.dart

      - name: Generate Supported API Matrix
        run: dart run ./bin/generate_supported_api_matrix.dart

      - name: Generate Lexicon Docs
        run: dart run ./bin/generate_lexicon_docs.dart

      - name: Format
        run: |
          dart format packages/lexicon
          dart format packages/atproto
          dart format packages/bluesky
          dart format packages/bluesky_chat

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "[Scheduled] Pull Latest Lexicons"
          title: "[Scheduled] Pull Latest Lexicons"
          branch: pull-latest-lexicons
          base: main
          labels: Github Actions
          assignees: "${{ github.actor }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
