name: Sync Lexicons

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"

jobs:
  update-lexicons:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Delete Old Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin
          if git show-ref --quiet refs/remotes/origin/chore-sync-lexicons; then
            git push origin --delete chore-sync-lexicons
          fi

      - name: Create New Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch -c chore-sync-lexicons
          git push -u origin chore-sync-lexicons

      - uses: dart-lang/setup-dart@v1.3

      - name: Install dependencies
        run: dart pub get

      - name: Sync Lexicons
        run: dart run ./scripts/sync_lexicons.dart
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "chore: Sync Lexicon Data"
          title: "chore: Sync Lexicon Data"
          branch: chore-sync-lexicons
          base: main
          labels: Github Actions
          assignees: "${{ github.actor }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
